name: Release

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env: 
        SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1



    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Generate Changelog
      run: npm run changelog

    - name: Build Electron app
      run: npm run build -- --publish-always
      env: 
        SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}


    


