

name: Build/Release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM, and Yarn (Ubuntu)
        if: runner.os == 'Linux'
        uses: actions/setup-node@v2
        with:
          node-version: '20'
    
      - name: Install Node.js, NPM, and Yarn (macOS and Windows)
        if: runner.os != 'Linux'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        if: runner.os != 'Linux'
        run: npm install

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
            rm -rf node_modules
            npm install
            chmod +x ./node_modules/app-builder-bin/linux/x64/app-builder


      - name: Audit Fix
        run: npm audit fix --force

      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
