

name: Build/Release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '20.13.1'
      - name: Install dependencies
        run: npm install



      - name: Build/Release Electron app
        run: npx electron-builder --publish always --log-level debug
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
