name: secrets test
on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env: 
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Read a variable
        run: echo "SUPABASE_URL value is ${{ vars.SUPABASE_URL }}"

      - name: Read secrets
        run: echo "My secrets are ${{ secrets.SUPABASE_ANON_KEY }} and ${{ secrets.SECRET_KEY }}"
