name: Release

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      
    - name: Install Snapcraft
      if: matrix.platform == 'linux'
      run: |
        sudo apt update
        sudo apt install -y snapd
        sudo snap install snapcraft

    - name: Build Snap
      if: matrix.platform == 'linux'
      run: snapcraft
      

    - name: Generate Changelog
      run: npm run changelog

    - name: Install Wine (required for Windows builds)
      if: matrix.platform == 'win32'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine64 wine32

    - name: Build Electron app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        npm run build -- --${{ matrix.platform }}
        

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: ./CHANGELOG.md
        draft: false
        prerelease: false

